on:
  workflow_call:
    outputs:
      image:
        value: ${{ jobs.containerize.outputs.image }}

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ github.run_id }}

jobs:
  containerize:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ env.IMAGE }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
