on:
  workflow_call:
    outputs:
      image:
        value: ghcr.io/${{ github.repository }}:${{ jobs.containerize.outputs.digest }}

jobs:
  containerize:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        id: build
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.run_id }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
