on:
  workflow_call:
    inputs:
      tier:
        type: string
        required: true
        description: |
          defines which values.yml is applied.
          is also used to compute the name of the github environment and helm release name
      image:
        type: string
        required: true
        description: docker image to be deployed

env:
  ENVIRONMENT: ${{ inputs.tier == 'review' && format('pr-{0}', github.event.pull_request.number) || inputs.tier }}

jobs:
  deploy:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ env.ENVIRONMENT }}
      cancel-in-progress: true
    environment:
      name: ${{ env.ENVIRONMENT }}
      url: https://${{ github.event.repository.name }}-${{ env.ENVIRONMENT }}.homelabx.uk
    steps:
      - uses: actions/checkout@v4
      - run: echo TODO use helm values for tier ${{ inputs.tier }}.yml #TODO remove this line
      - run: >
          helm upgrade ${{ github.event.repository.name }}-${{ env.ENVIRONMENT }} ./chart
          --install --atomic --timeout 300s
          --create-namespace -n ${{ github.event.repository.name }}
          --set image=${{ inputs.image }}
          --set ingress.url=${{ jobs.deploy.environment.url }}
