on:
  workflow_call:
    inputs:
      tier:
        type: string
        required: true
        description: defines which values.yml is applied
      environment:
        type: string
        required: true
        description: |
          github environment for overriding secrets
          also used as a suffix to the helm release
      image:
        type: string
        required: true
        description: docker image to be deployed

env:
  INGRESS_HOST: ${{ format(inputs.environment == 'prod' && '{0}' || '{0}-{1}', github.event.repository.name, inputs.environment) }}.homelabx.uk

jobs:
  deploy:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.environment }}
      cancel-in-progress: true
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ env.INGRESS_HOST }}
    steps:
      - uses: actions/checkout@v4
      - run: echo TODO use helm values for tier ${{ inputs.tier }}.yml #TODO remove this line
      - run: >
          helm upgrade ${{ github.event.repository.name }}-${{ inputs.environment }} ./chart
          --install --atomic --timeout 300s
          --create-namespace -n ${{ github.event.repository.name }}
          --set image=${{ inputs.image }}
          --set ingress.host=${{ env.INGRESS_HOST }}
