on:
  workflow_dispatch:
  push:
    branches:
      - main
      # add branches or tags if needed (depends on the branching model)

jobs:
  containerize:
    uses: ./.github/workflows/.containerize.yml
    permissions:
      contents: read
      packages: write
  deploy-prod:
    needs: containerize
    uses: ./.github/workflows/.deploy.yml
    with:
      tier: prod
      image: ${{ needs.containerize.outputs.image }}
