on:
  pull_request:

jobs:
  containerize:
    uses: ./.github/workflows/.containerize.yml
    permissions:
      contents: read
      packages: write
  deploy-review:
    needs: containerize
    uses: ./.github/workflows/.deploy.yml
    with:
      environment: pr-${{ github.event.pull_request.number }}
      appName: ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}
      image: ${{ needs.containerize.outputs.image }}
