on:
  workflow_dispatch:
  push:
    branches:
      - main
      # add branches or tags if needed (depends on the branching model)

jobs:
  containerize:
    uses: ./.github/workflows/.containerize.yml
    permissions:
      contents: read
      packages: write
  deploy-prod:
    needs: containerize
    runs-on: self-hosted
    environment:
      name: prod
      url: https://${{ github.event.repository.name }}.homelabx.uk
    steps:
      - uses: actions/checkout@v4
      - run: helm upgrade --install --atomic --timeout 300s --create-namespace -n ${{ github.event.repository.name }} --set image="${{ needs.containerize.outputs.image }}" ${{ github.event.repository.name }} ./chart
