on:
  pull_request:

jobs:
  containerize:
    uses: ./.github/workflows/.containerize.yml
    permissions:
      contents: read
      packages: write
  deploy-review:
    needs: containerize
    runs-on: self-hosted
    environment:
      name: pr-${{ github.event.pull_request.number }}
      url: https://${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}.homelabx.uk
    steps:
      - uses: actions/checkout@v4
      - run: helm upgrade --install --atomic --timeout 300s --create-namespace -n ${{ github.event.repository.name }} --set image="${{ needs.containerize.outputs.image }}" ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }} ./chart
