on:
  pull_request:

jobs:
  containerize:
    uses: ./.github/workflows/.containerize.yml
    permissions:
      contents: read
      packages: write
  deploy-review:
    needs: containerize
    uses: ./.github/workflows/.deploy.yml
    with:
      environment: pr-${{ github.event.pull_request.number }}
      tier: prod # change this to "prod" for example to test the review app with prod config #TODO change back to review
      image: ${{ needs.containerize.outputs.image }}
