on:
  pull_request_target:
    types:
      - closed

jobs:
  destroy-review:
    runs-on: self-hosted
    steps:
      - run: helm uninstall --wait -n ${{ github.event.repository.name }} ${{ github.event.repository.name }}-pr-${{ github.event.pull_request.number }}
